"""criar tabela mensagens

Revision ID: 2d1f76ab45f0
Revises: 
Create Date: 2025-06-08 10:45:10.366362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d1f76ab45f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('pergunta', sa.String(), nullable=True),
    sa.Column('resposta', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_cliente_id'), 'mensagens', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_mensagens_id'), 'mensagens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagens_id'), table_name='mensagens')
    op.drop_index(op.f('ix_mensagens_cliente_id'), table_name='mensagens')
    op.drop_table('mensagens')
    # ### end Alembic commands ###
